# Generated by Django 5.0.1 on 2024-01-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_settings_description_alter_settings_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description1',
            field=models.TextField(default=1, verbose_name='1_Описания заголовка_2 '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='description2',
            field=models.TextField(default=1, verbose_name='2_Описания заголовка_2 '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='description3',
            field=models.TextField(default=1, verbose_name='3_Описания заголовка_2 '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image2',
            field=models.ImageField(default=1, upload_to='portrait1/', verbose_name='Фотография 2го заголовка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title2',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок_2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(verbose_name='Описание сайта'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image',
            field=models.ImageField(upload_to='portrait/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Заголовок сайта'),
        ),
    ]
