# Generated by Django 5.0.1 on 2024-01-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_settings_description1_settings_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='number1',
            field=models.IntegerField(default=1, verbose_name='Цифры для Winning award (Награда)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='number2',
            field=models.IntegerField(default=1, verbose_name='Цифры для Complete project (Полный проект)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='number3',
            field=models.IntegerField(default=1, verbose_name='Цифры для Client review (Обзор клиента)'),
            preserve_default=False,
        ),
    ]
